path: /home/ares/MISAHUB/yolo_v8/	# Specify the path to your model
train: train/						# Specify the training directory
val: valid/							# Specify the validation directory (Mandatory if training the model)

# Classes 
nc: 1 # replace based on your dataset's number of classes 

# Class names 
# replace all class names with your own classes' names 
names: ['bleeding']
